version: '3'
services:
  web:
    restart: unless-stopped
    build: .
    env_file:
      - .env
    ports :
     - "80:80"
    volumes:
     - ./app:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini
