# Main 
default:
  controller: Main
  action: home

media:
  controller: Media
  action: mediaView

# Authentification
login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

confirm:
  controller: Auth
  action: confirmAccount

forgot:
  controller: Auth
  action: viewForgotPwd

forgot-confirmation:
  controller: Auth
  action: forgotPassword

reset-password:
  controller: Auth
  action: viewResetPassword

confirm-reset-password:
  controller: Auth
  action: resetPassword

# Back
back-read-user:
  controller: Users
  action: readUser

back-create-user:
  controller: Users
  action: createUser

back-delete-user:
  controller: Users
  action: deleteUser

back-update-user:
  controller: Users
  action: updateUser

back-get-user:
  controller: Users
  action: getUser

back-view-user:
  controller: Users
  action: view

back-view-category:
  controller: Categorys
  action: viewCategory

back-create-category:
  controller: Categorys
  action: createCategory

elementard-view:
  controller: Cms
  action: cmsView

elementard-getdata:
  controller: Cms
  action: getAjaxData

elementard-getall:
  controller: Cms
  action: readAll
  
elementard/read:
  controller: CmsUser
  action: getListPage

media-getdata:
  controller: Media
  action: getMediaByID

back-read-six-elementard:
  controller: Cms
  action: getSix

back-read-category:
  controller: Categorys
  action: readCategory

back-delete-category:
  controller: Categorys
  action: deleteCategory

back-update-category:
  controller: Categorys
  action: updateCategory

back-get-category:
  controller: Categorys
  action: getCategory

back-view-gestionfront:
  controller: GestionFronts
  action: view

back-create-gestionfront:
  controller: GestionFronts
  action: createContent

back-get-content:
  controller: GestionFronts
  action: getContent

back-gestion-background:
  controller: GestionFronts
  action: createBackground

back-gestion-picture:
  controller: GestionFronts
  action: createPicture
  
back-view-dashboard:
  controller: Dashboard
  action: viewDashboard
  
back-testo:
    controller: Dashboard
    action: createUserCreationChart

back-view-elementard:
  controller: Cms
  action: viewCrud

back-read-elementard:
  controller: Cms
  action: readAll

back-delete-cms:
  controller: Cms
  action: deleteCms

back-get-cms:
  controller: Cms
  action: getCms

back-create-comments:
  controller: Comments
  action: createComments

# Sitemap
sitemap:
  controller: Sitemap
  action: sitemap

# Footer
legals:
  controller: Main
  action: legals

confidentiality:
  controller: Main
  action: confidentiality

about-us:
  controller: Main
  action: aboutUs

# Memento
memento:
  controller: Memento
  action: mementoView


