# Main 
default:
  controller: Main
  action: home

media:
  controller: Main
  action: media

# Authentification
login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

confirm:
  controller: Auth
  action: confirmAccount

forgot:
  controller: Auth
  action: viewForgotPwd

forgot-confirmation:
  controller: Auth
  action: forgotPassword

reset-password:
  controller: Auth
  action: viewResetPassword

confirm-reset-password:
  controller: Auth
  action: resetPassword

# Error pages
404:
  controller: Error
  action: error404

403:
  controller: Error
  action: error403

500:
  controller: Error
  action: error500

401:
  controller: Error
  action: error401

410:
  controller: Error
  action: error410

create-review:
  controller: Cms
  action: userReview

back-read-user:
  controller: Users
  action: readUser

back-create-user:
  controller: Users
  action: createUser

back-delete-user:
  controller: Users
  action: deleteUser

back-update-user:
  controller: Users
  action: updateUser

back-get-user:
  controller: Users
  action: getUser

back-view-user:
  controller: Users
  action: view

back-view-category:
  controller: Categorys
  action: view

back-create-category:
  controller: Categorys
  action: createCategory

back-read-category:
  controller: Categorys
  action: readCategory

back-delete-category:
  controller: Categorys
  action: deleteCategory

back-update-category:
  controller: Categorys
  action: updateCategory

back-get-category:
  controller: Categorys
  action: getCategory

back-view-gestionfront:
  controller: GestionFronts
  action: view

back-create-gestionfront:
  controller: GestionFronts
  action: createContent

back-get-content:
  controller: GestionFronts
  action: getContent

back-gestion-background:
  controller: GestionFronts
  action: createBackground
# Sitemap
sitemap:
  controller: Sitemap
  action: sitemap

create-review:
   controller: Main
   action: createReview

legals:
  controller: Main
  action: legals

confidentiality:
  controller: Main
  action: confidentiality

about-us:
  controller: Main
  action: aboutUs

categories:
  controller: Categorys
  action: pageCategory
