default:
  controller: Main
  action: home

media:
  controller: Main
  action: media
  
review:
  controller: Main
  action: review

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

s-inscrire:
  controller: Auth
  action: register

404:
  controller: Error
  action: error404  

403:
  controller: Error
  action: error403

500:
  controller: Error
  action: error500

401:
  controller: Error
  action: error401

410:
  controller: Error
  action: error410

backoffice:
  controller: Users
  action: readUser

create:
  controller: Users
  action: createUser

delete:
  controller: Users
  action: deleteUser

update:
  controller: Users
  action: updateUser

user:
  controller: Users
  action: getUser

read:
  controller: Users
  action: readUser

view:
  controller: Users
  action: view