default:
  controller: Main
  action: home

media:
  controller: Main
  action: media
  
create-review:
  controller: Cms
  action: userReview

new-admin-review:
  controller: Cms
  action: adminReview

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

s-inscrire:
  controller: Auth
  action: view

404:
  controller: Error
  action: error404  

403:
  controller: Error
  action: error403

500:
  controller: Error
  action: error500

401:
  controller: Error
  action: error401

410:
  controller: Error
  action: error410

backoffice:
  controller: Users
  action: readUser

create:
  controller: Users
  action: createUser

delete:
  controller: Users
  action: deleteUser

update:
  controller: Users
  action: updateUser

user:
  controller: Users
  action: getUser

read:
  controller: Users
  action: readUser

view:
  controller: Users
  action: view

register:
  controller: Auth
  action: register

confirm:
   controller: Auth
   action: confirmAccount
   
category:
  controller: Categorys
  action: view

tam:
  controller: Categorys
  action: createCategory

cateread:
  controller: Categorys
  action: readCategory

catedelete:
  controller: Categorys
  action: deleteCategory

tap:
  controller: Categorys
  action: getCategory

updatetam:
  controller: Categorys
  action: updateCategory

forgot:
   controller: Auth
   action: view_forgotPwd

forgot-confirmation:
   controller: Auth
   action: forgotPassword

reset-password:
   controller: Auth
   action: view_resetPassword

confirm-reset-password:
   controller: Auth
   action: resetPassword