# Main 
default:
  controller: Main
  action: home

media:
  controller: Main
  action: media

# Authentification
login:
  controller: Auth
  action: login

logout:
  controller: Auth
  action: logout

register:
  controller: Auth
  action: register

confirm:
  controller: Auth
  action: confirmAccount

forgot:
  controller: Auth
  action: view_forgotPwd

forgot-confirmation:
  controller: Auth
  action: forgotPassword

reset-password:
  controller: Auth
  action: view_resetPassword

confirm-reset-password:
  controller: Auth
  action: resetPassword

# Error pages
404:
  controller: Error
  action: error404  

403:
  controller: Error
  action: error403

500:
  controller: Error
  action: error500

401:
  controller: Error
  action: error401

410:
  controller: Error
  action: error410

# Backoffice
back-backoffice:
  controller: Users
  action: readUser

back-create:
  controller: Users
  action: createUser

back-delete:
  controller: Users
  action: deleteUser

back-update:
  controller: Users
  action: updateUser

back-user:
  controller: Users
  action: getUser

back-read:
  controller: Users
  action: readUser

back-view:
  controller: Users
  action: view
   
back-category:
  controller: Categorys
  action: view

back-tam:
  controller: Categorys
  action: createCategory

back-cateread:
  controller: Categorys
  action: readCategory

back-catedelete:
  controller: Categorys
  action: deleteCategory

back-tap:
  controller: Categorys
  action: getCategory

back-updatetam:
  controller: Categorys
  action: updateCategory

# Sitemap
sitemap:
  controller: Sitemap
  action: sitemap